name: chat
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  flutter_inappwebview: ^5.8.0
  
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.3.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.0.9
  get: ^4.6.6
  image_picker: ^1.0.0
  intl: ^0.18.1
  loader_overlay: ^2.1.0
  path: ^1.8.0
  path_provider: ^2.0.11
  pattern_formatter: ^3.0.0
  permission_handler: ^10.0.0
  pinput: ^2.2.23
  share_plus: ^7.0.2
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  url_launcher: ^6.0.18
  google_fonts: ^5.1.0
  animated_bottom_navigation_bar: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  
